# Generated by Django 5.0.7 on 2024-07-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devTools', '0001_initial'),
        ('ideas', '0002_ideastar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devTools.devtool', verbose_name='예상 개발툴'),
        ),
    ]
