# Generated by Django 5.0.7 on 2024-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
            ],
        ),
    ]
