# Generated by Django 5.0.7 on 2024-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
