# Generated by Django 5.0.7 on 2024-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['title', 'star', 'time']},
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('멜로/로맨스', '멜로/로맨스'), ('코미디', '코미디'), ('역사', '역사'), ('SF', 'SF'), ('스릴러', '스릴러'), ('미스터리', '미스터리'), ('드라마', '드라마'), ('공포', '공포'), ('뮤지컬', '뮤지컬'), ('판타지', '판타지'), ('애니메이션', '애니메이션'), ('스포츠', '스포츠'), ('범죄', '범죄')], default='로맨스', max_length=10),
        ),
    ]
